### ISSUE TITLE
Open Budget municipality of Madrid

### ISSUE THREAD

**Issue by dcabo** [os-data/registry#41]
There’s no standard format for municipal budget data in Spain, but the underlying structure is the same, since it’s set by law. The Madrid data is quite detailed and is a good example: 
- [2015 budget](http://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=af62db13cb659410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD) as XLS
- [2012-2014 budgets](http://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=14f285e4b1204410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD), as XLS

**Comment by danfowler** [comment]
Dataset created: https://github.com/os-data/madrid-municipal-gastos
